# Robot parameters
tcp_speed: 0.03

# Gripper parameters
tcp2fingertip: 0.32488 # distance from tcp to gripper fingertip 0.32601
opening_per_count: 0.00065 # gripper stroke opening per rPr count
finger_thickness: 0.008
max_opening: 0.3 # max stroke of gripper excluding finger thickness
gripper_speed: 0.1 # value between 0.013 and 0.100
gripper_force: 10 # value between 0 and 100

# Object dimension
object_thickness: 0.0057 #0.01 # object thickness in meters 0.0057
################################################
object_length: 0.023 # object length in meters #flat surface: 0.023; curved surface: 0.027
################################################

# Initial configuration
#################################################
delta_0: 0.015 #0.0425 # distance from fingertip to object tip within gripper #flat surface: 0.015 curved surface: 0.015
theta_0: 46 # 40; flat surface: 40; curved surface: 47
#################################################

# Intermediate configuration
#################################################
psi_regrasp: 37 #45 #flat surface: 45; curved surface: 35
theta_tilt: 22 #30 #19 flat surface: 27; curved surface: 30
tuck: 10 #flat surface: 7; curved surface: 7
#################################################

# Action axis
axis: [1, 0, 0]

# Simulation
sim: 0

'''
# Robot parameters
tcp_acc: 0.05
tcp_vel: 0.05

# Gripper parameters
tcp2fingertip: 0.28118 #0.275 # distance from tcp to gripper fingertip
gripper_speed: 0.1 # value between 0.013 and 0.100
gripper_force: 10 # value between 0 and 100

# Object dimension
object_thickness: 0.0057 #0.01 # object thickness in meters
object_length: 0.023 # object length in meters

# Initial configuration
delta_0: 0.022 #0.0425 # distance from fingertip to object tip within gripper
theta_0: 40

# Intermediate configuration
psi_regrasp: 38
theta_tilt: 25
tuck: 6

# Action axis
axis: [1, 0, 0]
'''
